### ISSUE TITLE
[Bug Report] Button组件出现Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by rtmax0** [mallfoundry/taroify#595]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

H5

### 你正在使用的 Taroify 版本是多少

0.1.0-alpha.11

### 描述一下您遇到的问题以及重现步骤

在页面上引入<Button variant='text' color='info'>信息按钮</Button>，在开发模式下会出现：

vendors-node_modules_taro_h5_prebundle_chunk-ECDUEMIU_js._chunkhash_.js:140  Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Button`. See https://reactjs.org/link/warning-keys for more information.
    at TaroViewCore
    at Button (webpack-internal:///./node_modules/.pnpm/registry.npmmirror.com+@taroify+core@0.1.0-alpha.11_@tarojs+components@3.6.14_@tarojs+taro@3._m4vpqgyur63uodpvnkqps5vlgq/node_modules/@taroify/core/button/button.js:122:7)
    at taro-view-core
    at ReactComponent (http://localhost:10086/js/vendors-node_modules_taro_h5_prebundle_chunk-PW7VFE46_js._chunkhash_.js:273:13)
    at TaroViewCore
    at Index (webpack-internal:///./src/pages/home/index.tsx:35:55)
    at div
    at PageWrapper (http://localhost:10086/js/vendors-node_modules_taro_h5_prebundle_chunk-F2C5UEC5_js._chunkhash_.js:259:17)
    at App (webpack-internal:///./src/app.ts:15:23)
    at AppWrapper (http://localhost:10086/js/vendors-node_modules_taro_h5_prebundle_chunk-F2C5UEC5_js._chunkhash_.js:333:13)

### 你知道如何解决这个问题吗

Yes

### 您是否愿意参与修复这个问题，并创建一个 PR

None

### 修复这个问题的解决方案

在 button.tsx 文件useButtonChildren方法中，对应map返回的<View>加入 key={index} 可解决。

diff --git a/packages/core/src/button/button.tsx b/packages/core/src/button/button.tsx
index 563293f4..e17c43de 100644
--- a/packages/core/src/button/button.tsx
+++ b/packages/core/src/button/button.tsx
@@ -92,7 +92,7 @@ function useButtonChildren(options: UseButtonChildrenOptions = {}) {
             return appendButtonIconClassname(child, prefixClassname("button__icon--left"))
           }
           return (
-            <View className={prefixClassname("button__text")}>{child}</View>
+            <View key={index} className={prefixClassname("button__text")}>{child}</View>
           )
         })
       }

**Comment by Pilotager** [comment]
@rtmax0 方便提交一个 PR 么

**Comment by rtmax0** [comment]
> @rtmax0 方便提交一个 PR 么

行，我试试，其实就是加一个 key={index}  的事。

**Comment by rtmax0** [comment]
@Pilotager 请确认 PR 。

**Comment by rtmax0** [comment]
@Pilotager 方便加WX交流一下？我的WX：rtmax0，谢谢
