### ISSUE TITLE
Popup支付宝真机调试下报错[Bug Report] 

### ISSUE THREAD

**Issue by zzyzjc** [mallfoundry/taroify#641]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

支付宝小程序

### 平台/设备/浏览器

Android手机、苹果手机 都是必现

### 你正在使用的 Taroify 版本是多少

0.1.1-alpha.0

### 描述一下您遇到的问题以及重现步骤

页面引入后，在开发者工具中调试是没有问题的，真机调试就会报错。
抖音、微信 都是没有问题的，可以正常工作。只有支付宝是出现了这样的问题
`vendors-node_modules_taro_alipay_prebundle_chunk-DW3YG3Z2_js.js:2129

TypeError: r is not a function
    at h (index.worker.js:274:8571)
    at ro (index.worker.js:274:73303)
    at Fe (index.worker.js:274:107259)
    at index.worker.js:307:231122
    at index.worker.js:307:230655
    at la (index.worker.js:274:58713)
    at Rs (index.worker.js:274:85356)
    at da (index.worker.js:274:58386)
    at Na (index.worker.js:274:66932)
    at Ma (index.worker.js:274:66282)
    at Br (index.worker.js:274:88015)
    at c (index.worker.js:274:2633)
    at l (index.worker.js:274:2407)
    at le (index.worker.js:274:5136)`

### 你知道如何解决这个问题吗

None

### 您是否愿意参与修复这个问题，并创建一个 PR

None

**Comment by hbztd** [comment]
预览不会报错，可以正常使用，可能是支付宝的本身问题

**Comment by hbztd** [comment]
@Pilotager close
